# Generated by Django 5.2.5 on 2025-08-14 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('url_shortener_app', '0002_shorturl_clicks'),
    ]

    operations = [
        migrations.AddField(
            model_name='shorturl',
            name='expiration',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
