# Generated by Django 5.2.5 on 2025-08-14 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('url_shortener_app', '0003_shorturl_expiration'),
    ]

    operations = [
        migrations.AddField(
            model_name='shorturl',
            name='last_clicked',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
