# Generated by Django 5.2.5 on 2025-08-14 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('url_shortener_app', '0004_shorturl_last_clicked'),
    ]

    operations = [
        migrations.AddField(
            model_name='shorturl',
            name='password',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
