# Generated by Django 5.2.5 on 2025-08-17 12:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('url_shortener_app', '0005_shorturl_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='URLClick',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField()),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('clicked_at', models.DateTimeField(auto_now_add=True)),
                ('url', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='click_logs', to='url_shortener_app.shorturl')),
            ],
            options={
                'unique_together': {('url', 'ip_address')},
            },
        ),
    ]
